name: Manually Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "us"
        env:
          HD_BOT_TOKEN: ${{secrets.BOT_TOKEN}}
          HD_OWNER_ID: "1398302310"
          HD_TELEGRAM_API: "2452280"
          HD_TELEGRAM_HASH: "6c553a78aca54e22a50d2f4288cc118b"
          HD_DATABASE_URL: "mongodb+srv://user:41044104@cluster0l.pcf46se.mongodb.net/?retryWrites=true&w=majority"
          HD_BASE_URL: "https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com"
          HD_STOP_DUPLICATE: "True"
          HD_IS_TEAM_DRIVE: "True"
          HD_USE_SERVICE_ACCOUNTS: "True"
          HD_VIEW_LINK: "True"
          HD_UPSTREAM_REPO: "https://fine008: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@github.com/fine008/PROJECT-EDITH"
          HD_UPSTREAM_BRANCH: "beta"
          HD_RESTART_COMMAND: "release"
