name: Manually Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "us"
        env:
          HD_BOT_TOKEN: "5932926601:AAHVnnl6kNepzUGkmxnMzMeu1P9jFPUsusk"
          HD_OWNER_ID: "5755368058"
          HD_TELEGRAM_API: "16501053"
          HD_TELEGRAM_HASH: "d8c9b01c863dabacc484c2c06cdd0f6e"
          HD_DATABASE_URL: "mongodb+srv://SHELL:SHELL@cluster0.pz2edgr.mongodb.net/?retryWrites=true&w=majority"
          HD_BASE_URL: "https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com"
          HD_STOP_DUPLICATE: "True"
          HD_IS_TEAM_DRIVE: "False"
          HD_USE_SERVICE_ACCOUNTS: "False"
          HD_VIEW_LINK: "True"
          HD_SOURCE_LINK: "True"
          HD_STATUS_UPDATE_INTERVAL: "2"
          HD_UPSTREAM_REPO: "https://babupakkakivellu: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:@github.com/babupakkakivellu/Diffusionbabu"
          HD_UPSTREAM_BRANCH: "beta"
